### ISSUE TITLE
Unrecognised arguments

### ISSUE THREAD

**Issue by alfanhui** [miigotu/certbot-dns-godaddy#1]
Hey,

Thanks for making this public. I haven't been able to get it to run on certbot 1.15.0 (PYTHON). 
Can you check this command, the readme states double backslash \\\ which doesn't work in the terminal. I wonder if theres something less missing?

Using the named schema as well due to version:
COMMAND:
```
$ certbot certonly \
>   --authenticator certbot-dns-godaddy:dns-godaddy \
>   --certbot-dns-godaddy:dns-godaddy-credentials /path/to/creds.ini \
>   --dns-godaddy-propagation-seconds 900 \
>   --keep-until-expiring --non-interactive --expand \
>   --server https://acme-v02.api.letsencrypt.org/directory \
>   -d 'example.com' \
>   -d '*.example.com'
```
ERR:
```
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --certbot-dns-godaddy:dns-godaddy-credentials /path/to/creds.ini --dns-godaddy-propagation-seconds 900
```

Cheers,
Alfanhui

**Comment by miigotu** [comment]
Maybe you have certbot installed for both python2.7 and python3, and when you call certbot it's running certbot from python2. This module only works with python3

**Comment by miigotu** [comment]
I will call a debug command of that later and post you the output.

**Comment by alfanhui** [comment]
Hey, thanks for replying.

I have managed to resolve it. I installed certbot using the python method: https://certbot.eff.org/lets-encrypt/otherpip-other
What I hadn't done is install this plugin to the virtualenv setup by certbot in python:

```
sudo /opt/certbot/bin/pip install certbot-dns-godaddy
```
The commands are now reconised and working.
Cheers!
