### ISSUE TITLE
acme record doesn't get created

### ISSUE THREAD

**Issue by saraswat40** [miigotu/certbot-dns-godaddy#17]
I'm on ubuntu 22.04. I installed certbot-dns-godaddy in a virtual environment as described here:
https://github.com/miigotu/certbot-dns-godaddy/issues/6
and also called the certbot as described in that post. But the txt record never gets created. I increased the propagation seconds to 2000 but I am checking the godaddy console directly so that shouldn't matter. I have also verified my godaddy api keys and they are also good.

**Comment by miigotu** [comment]
`~/certbot/bin/certbot certonly --authenticator dns-godaddy --dns-godaddy-credentials $FILENAME --dns-godaddy-propagation-seconds 900 --keep-until-expiring --non-interactive --expand --server https://acme-v02.api.letsencrypt.org/directory -d '$DOMAINNAME'`

and check logs in /var/log/letsencrypt

I no longer use this method, so without logs or an error there isn't much I can help with. I use nginx-proxy and a docker connector now that auto creates explicit certificates.

**Comment by naivefun** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_godaddy.py", line 87, in add_txt_record
    self._find_domain_id(ex.registered_domain)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 102, in _find_domain_id
    raise result1
certbot.errors.PluginError: Error determining zone identifier for reapi.io: 401 Client Error: Unauthorized for url: https://api.godaddy.com/v1/domains/xxx.io.
2022-12-08 07:56:38,783:DEBUG:certbot._internal.display.obj:Notifying user: Waiting 900 seconds for DNS changes to propagate

The command worked a few months before but now stop working.

Possible cause: https://github.com/win-acme/win-acme/issues/1794
