### ISSUE TITLE
does not work until I create symlinks

### ISSUE THREAD

**Issue by rbgnr111** [miigotu/certbot-dns-godaddy#18]
certbot wasn't able to find this package until I created the following symlinks:

 ln -s /usr/local/lib/python3.9/site-packages/certbot_dns_godaddy.py /usr/lib/python3.9/site-packages/certbot_dns_godaddy.py

ln -s /usr/local/lib/python3.9/site-packages/certbot_dns_godaddy-0.2.2.dist-info /usr/lib/python3.9/site-packages/certbot_dns_godaddy-0.2.2.dist-info

**Comment by miigotu** [comment]
/use/local vs /usr is dependent on how you install python. You have to install the package with the python you want to use it with. Installing python manually with the incorrect makefile arguments will also change that, we don't do any handling of the paths in the package, it's done by pip.
