### ISSUE TITLE
Certbot breaks when installed with Python3.10

### ISSUE THREAD

**Issue by kcrtr** [miigotu/certbot-dns-godaddy#19]
**OS: Ubuntu 22.04**

Steps to recreate:

I followed the official steps to install Certbot with pip. (I can not get snap to work in my WSL2 distro so this was the work around)
https://certbot.eff.org/instructions?ws=other&os=pip

Up to this point when I run ` sudo certbot --version` it outputs correctly as expected. (See below)

![image](https://user-images.githubusercontent.com/75222674/204583418-83086072-e77f-4b73-a5f5-987153bb1648.png)

When I install this package using `sudo /opt/certbot/bin/pip install certbot-dns-godaddy`  and try to run any certbot command it returns this following:

![image](https://user-images.githubusercontent.com/75222674/204583845-3be205e9-fa2c-48dd-a3ee-b974141a91a3.png)

When I run  `sudo /opt/certbot/bin/pip uninstall certbot-dns-godaddy` and then ` sudo certbot --version` it once again outputs correctly as expected.

**Comment by karrycrtr** [comment]
> It doesn't like certbot 2.0.0.
> 
> I did
> 
> ```
> pip uninstall certbot
> pip uninstall acme
> pip install acme==1.3.20
> pip install certbot==1.3.20
> ```
> 
> and it stopped complaining and seems to work

I'll try this as well... thank you!

**Comment by karrycrtr** [comment]
> install certbot==1.3.20

Small correction to the version number but it worked! Thanks a mil @tomldickson!

```
pip uninstall certbot
```
```
pip uninstall acme
```
```
pip install acme==1.32.0
```
```
pip install certbot==1.32.0
```

**Comment by karrycrtr** [comment]
For anyone using the same method I used the commands would be as follows:

```
/opt/certbot/bin/pip uninstall certbot
```
```
/opt/certbot/bin/pip uninstall acme
```
```
/opt/certbot/bin/pip install acme==1.32.0
```
```
/opt/certbot/bin/pip install certbot==1.32.0
```

And to install the plugin use:

```
/opt/certbot/bin/pip install certbot-dns-godaddy
```

**Comment by miigotu** [comment]
You shouldn't need to install certbot at all, the plugin I believe installs what it wants, so just pip install the plugin.

**Comment by miigotu** [comment]
I pinned it to less than 2.0.0 for now, just pip install the plugin and it will get the correct certbot.
