### ISSUE TITLE
Plugin does not detect API errors?

### ISSUE THREAD

**Issue by aalku** [miigotu/certbot-dns-godaddy#21]
I did put the godaddy credentials wrong and it was obvious in the logs because of the 401 error from the API but the certbot execution didn't tell. It makes you wait until timeout then it just say the challenge failed and suggest to increase the timeout. It would help if it says "The API returned authentication error" or something. Thanks!

**Comment by miigotu** [comment]
None of that handling is done in this plugin, it is done in either lexicon, acme, or certbot itself.

**Comment by aalku** [comment]
I'm looking into it.

[Here](https://github.com/miigotu/certbot-dns-godaddy/blob/08f79d83b312c6426787ccf5614122f0cbce429d/certbot_dns_godaddy.py#L76C9-L76C23) you just `return` if `self._find_domain_id(ex.registered_domain)` fails but you rise an error if `self.provider.create_record(rtype='TXT', name=record_name, content=record_content)` fails.

Maybe the first call fails if the credentials are wrong and nobody notices because you didn't rise the error?

So the TXT register is not created but nobody knows as you just returned without error.

Maybe I'm totally wrong, I'm not testing it and my knowledge in this is very shallow. It's just an idea.

**Comment by miigotu** [comment]
There is a new version that uses the latest lexicon and certbot, which should fix this issue. If not, feel free to let me know in this issue and I will reopen. I no longer directly handle the record creation, it is handled inside lexicon and certbot, however there may arise an issue for users with multiple domains on GoDaddy with multiple endpoints. If so, we will handle that then.
