### ISSUE TITLE
hub.docker.com images all have "ENV QEMU_ARCH=x86_64" in layer 16

### ISSUE THREAD

**Issue by electricbrain-code** [miigotu/certbot-dns-godaddy#22]
All images on hub.docker.com are x86_64 binaries even though they are labelled arm64 etc.
The error is "exec /bin/sh: exec format error". Same for all binaries.

I think this is a bug in the multiarch build script. It shows up on layer 16:
"ENV QEMU_ARCH=x86_64" which I assume is the target architecture?

I'll have to build locally from source - doh!

It's a pity because it works really well on the Ryzen....

Cheers

**Comment by miigotu** [comment]
That comes directly from the certbot/certbot base. I just updated the build because it wasn't building, let's see if that fixes this issue.

**Comment by miigotu** [comment]
try tag latest and let me know if it works.

**Comment by miigotu** [comment]
Sorry, I'm not sure if you ever tested this but if you still have the issue let me know and I will reopen this issue.
