### ISSUE TITLE
requires sudo?

### ISSUE THREAD

**Issue by steveredden** [miigotu/certbot-dns-godaddy#5]
not sure if it was just me, but i'd get `authenticator not found` errors if i did not preface my call with `sudo`

```sh
sudo certbot certonly \
  --authenticator dns-godaddy \
  --dns-godaddy-credentials /path/to/my.ini \
  --dns-godaddy-propagation-seconds 900 \
  --keep-until-expiring --non-interactive --expand \
  --server https://acme-v02.api.letsencrypt.org/directory \
  -d 'example.com' \
  -d '*.example.com'
```

update readme?

**Comment by miigotu** [comment]
Ofc it will need sudo if the ini or output dir are not readable by the current user, or if you used sudo to do the pip install.
