### ISSUE TITLE
Missing command line flags

### ISSUE THREAD

**Issue by eduder** [miigotu/certbot-dns-godaddy#58]
Running under Ubuntu 22.04. Goal is to have GoDaddy DNS auth used to generate certs for several internal subdomains and have certbot install into Apache.

It seems like it doesn't like -a dns-godaddy or --authenticator dns-godaddy

`Missing command line flags. For non-interactive execution, you will need to specify a plugin on the command line.  Run with '--help plugins' to see a list of options, and see https://eff.org/letsencrypt-plugins for more detail on what the plugins do and how to use them.
`

~/certbot-dns-godaddy/bin/certbot --authenticator dns-godaddy --dns-godaddy-credentials /path/to/credentials.ini --dns-godaddy-propagation-seconds 900 --keep-until-expiring --non-interactive --expand --server https://acme-v02.api.letsencrypt.org/directory -d subdomain1.example.com -d subdomain2.example.com -d subdomain3.example.com -d subdomain4.example.com

**Comment by miigotu** [comment]
Try replacing `--authenticator dns-godaddy`
With `--dns-godaddy`

**Comment by huzaifamk** [comment]
@eduder `--authenticator dns-godaddy` works for me.

My full command:

`certbot certonly --authenticator dns-godaddy --dns-godaddy-credentials ./credentials.ini --dns-godaddy-propagation-seconds 900 --keep-until-expiring --non-interactive --expand --server https://acme-v02.api.letsencrypt.org/directory -d example.com
`
