### ISSUE TITLE
Error determining zone identifier for <mydomain.com>

### ISSUE THREAD

**Issue by codeguy** [miigotu/certbot-dns-godaddy#64]
I receive this error while generating a wildcard cert.

```
Error determining zone identifier for <mydomain.com>
```

This appears to be an error generated from the extended Lexicon library (I'm not a Python dev, so this is the best way I can articulate this). Do you know if it is possible for me to provide the DNS zone name, or to prompt Lexicon to lookup the zone name rather than guess it?

**Comment by codeguy** [comment]
So I've found how to do this using env variable `LEXICON_DELEGATED='mydomain.com'` but that still returns the same error. Perhaps an issue with the DNS zone setup with the DNS provider.

**Comment by codeguy** [comment]
Still a problem if you wanted to investigate, but I've written my own bash manual auth hooks to get around the problem for now. Closing this out.

**Comment by beardedfool** [comment]
@codeguy as the next guy, have you shared the solution anywhere please?
