### ISSUE TITLE
I am facing an error: unrecognized arguments

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [miigotu/certbot-dns-godaddy#9]
I ran 
`certbot certonly --authenticator dns-godaddy --dns-godaddy-credentials $FILENAME --dns-godaddy-propagation-seconds 900 --keep-until-expiring --non-interactive --expand --server https://acme-v02.api.letsencrypt.org/directory -d '$DOMAINNAME'`

But I am facing this Error:

> certbot: error: unrecognized arguments: --dns-godaddy-credentials $FILENAME --dns-godaddy-propagation-seconds 900

I am using certbot v1.22.0 and python v3.9 pip v20.3.4

**Comment by cheesekon** [comment]
same problem here

**Comment by lalo4ka** [comment]
same here

**Comment by TomiSzabo00** [comment]
that did not fix it for me :(

**Comment by miigotu** [comment]
> that did not fix it for me :(

This package must be installed with the same interpreter and user that installed certbot. They have to be in the same environment. If you used sudo to install certbot, you have to use sudo to install certbot-dns-godaddy. If you did not use sudo for one, you cant use it for either of them.

I suggest you remove certbot and just install this package, which will reinstall certbot at the right version and place.

```python
pip3 uninstall certbot certbot-dns-godaddy
pip3 install certbot-dns-godaddy
certbot certonly --authenticator dns-godaddy --dns-godaddy-credentials $FILENAME --dns-godaddy-propagation-seconds 900 --keep-until-expiring --non-interactive --expand --server https://acme-v02.api.letsencrypt.org/directory -d '$DOMAINNAME'
```

**Comment by TomiSzabo00** [comment]
Thank you so much! That worked fine for me!
